[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@morpho-blue/=lib/morpho-blue/src/",
    "@morpho-blue-snippets/=lib/morpho-blue-snippets/src/",
    "@aave-v3-core/protocol/=lib/aave-v3-core/contracts/protocol/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@morphoAave3Optimizer/=lib/morpho-aavev3-optimizer/"
    ]